[2025-08-14T06:33:01.326+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_main_script_runner.run_main_py scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T06:33:01.346+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_main_script_runner.run_main_py scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T06:33:01.347+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2025-08-14T06:33:02.000+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): run_main_py> on 2025-08-13 00:00:00+00:00
[2025-08-14T06:33:02.007+0000] {standard_task_runner.py:60} INFO - Started process 872 to run task
[2025-08-14T06:33:02.015+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_main_script_runner', 'run_main_py', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/weather_batch_dag.py', '--cfg-path', '/tmp/tmpkfsu3al7']
[2025-08-14T06:33:02.018+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask run_main_py
[2025-08-14T06:33:03.363+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_main_script_runner.run_main_py scheduled__2025-08-13T00:00:00+00:00 [running]> on host 3e49ce6b9cd3
[2025-08-14T06:33:07.992+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_main_script_runner' AIRFLOW_CTX_TASK_ID='run_main_py' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T06:33:08.184+0000] {logging_mixin.py:188} INFO - Running Python script: /opt/infra/pyspark_jobs
[2025-08-14T06:33:14.593+0000] {logging_mixin.py:188} INFO - STDOUT:
[2025-08-14T06:33:15.040+0000] {logging_mixin.py:188} INFO -  
[2025-08-14T06:33:15.041+0000] {logging_mixin.py:188} INFO - STDERR:
[2025-08-14T06:33:15.044+0000] {logging_mixin.py:188} INFO -  /usr/local/bin/python3: can't find '__main__' module in '/opt/infra/pyspark_jobs'
[2025-08-14T06:33:15.048+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_batch_dag.py", line 22, in run_weather_main
    raise RuntimeError(f"Script failed with exit code {result.returncode}")
RuntimeError: Script failed with exit code 1
[2025-08-14T06:33:15.352+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=weather_main_script_runner, task_id=run_main_py, execution_date=20250813T000000, start_date=20250814T063301, end_date=20250814T063315
[2025-08-14T06:33:15.927+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 34 for task run_main_py (Script failed with exit code 1; 872)
[2025-08-14T06:33:15.978+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T06:33:16.053+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
