[2025-08-13T10:29:42.682+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_main_script_runner.run_main_py manual__2025-08-13T10:29:40.624523+00:00 [queued]>
[2025-08-13T10:29:42.703+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_main_script_runner.run_main_py manual__2025-08-13T10:29:40.624523+00:00 [queued]>
[2025-08-13T10:29:42.704+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-08-13T10:29:42.731+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): run_main_py> on 2025-08-13 10:29:40.624523+00:00
[2025-08-13T10:29:42.738+0000] {standard_task_runner.py:60} INFO - Started process 1912 to run task
[2025-08-13T10:29:42.747+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_main_script_runner', 'run_main_py', 'manual__2025-08-13T10:29:40.624523+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/weather_batch_dag.py', '--cfg-path', '/tmp/tmpkob09mj1']
[2025-08-13T10:29:42.751+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask run_main_py
[2025-08-13T10:29:42.884+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_main_script_runner.run_main_py manual__2025-08-13T10:29:40.624523+00:00 [running]> on host b8abf4c23708
[2025-08-13T10:29:43.134+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_main_script_runner' AIRFLOW_CTX_TASK_ID='run_main_py' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T10:29:40.624523+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-13T10:29:40.624523+00:00'
[2025-08-13T10:29:43.135+0000] {logging_mixin.py:188} INFO - üöÄ Running Python script: /opt/infra/pyspark_apps/main.py
[2025-08-13T10:29:43.373+0000] {logging_mixin.py:188} INFO - üìÑ STDOUT:
[2025-08-13T10:29:43.374+0000] {logging_mixin.py:188} INFO -  
[2025-08-13T10:29:43.374+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è STDERR:
[2025-08-13T10:29:43.374+0000] {logging_mixin.py:188} INFO -  python3: can't open file '/opt/infra/pyspark_apps/main.py': [Errno 2] No such file or directory
[2025-08-13T10:29:43.375+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_batch_dag.py", line 22, in run_weather_main
    raise RuntimeError(f"Script failed with exit code {result.returncode}")
RuntimeError: Script failed with exit code 2
[2025-08-13T10:29:43.400+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_main_script_runner, task_id=run_main_py, execution_date=20250813T102940, start_date=20250813T102942, end_date=20250813T102943
[2025-08-13T10:29:43.421+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task run_main_py (Script failed with exit code 2; 1912)
[2025-08-13T10:29:43.454+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-13T10:29:43.491+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
